### ISSUE TITLE
smile :D team review

### ISSUE THREAD

**Issue by bw02184** [woorifisa-service-dev-3rd/frontend-1st-triple_roulette#15]
1. 디자인과 구현을 해보고 싶게 잘 만드신 것 같습니다! 이후 결과를 공유할 수 있는 기능을 추가하면 좋을 것 같습니다.

2. 모든 프로젝트 중에서 디자인을 가장 잘하신 것 같아요!! 그리고 처음에 하단버튼을 Push 하라는 간단한 안내가 있으면 좋을 것 같아요~!

3. 디자인 정말 잘 봤습니다. 슬롯머신에 맞게 성공부분이 있어서 금화가 쏟아진다거나 하면 더 재미있을것 같습니다.

**Comment by qbobl5** [comment]
1. 추후 결과 저장을 할 수 있도록 할 예정입니다!
2. 감사합니다. 안내창 꼭 반영하도록 하겠습니다~~!
3. 오 좋은 아이디어 감사합니다. ^0^
