### ISSUE TITLE
ppl-review

### ISSUE THREAD

**Issue by jyp-on** [woorifisa-service-dev-3rd/frontend-1st-triple_roulette#16]
- 디자인이나 애니메이션을 엄청 잘 만드신 것 같아요!
- 도박장같은 느낌을 너무 잘 표현한거 같아요
- 웹페이지가 브라우저의 크기를 변경하는 반응 속도가 많이 느린거 같은데 이유를 알고싶어요

**Comment by qbobl5** [comment]
실제로 페이지 반응 속도가 좀 느려서 개선해야 할 부분이라고 생각하고 있었는데, 좋은 지적 감사합니다!
칭찬도 감사합니다 ^__^..!!!
