### ISSUE TITLE
[피드백] 카지노에서 10만원 딴 썰 풀어드립니다

### ISSUE THREAD

**Issue by cbj0010** [woorifisa-service-dev-3rd/frontend-1st-triple_roulette#18]
반응형이 되면 너무 좋은 기획일거같아요!

디자인을 이미지로 넣은게 아니라 실제 구현하셨다니.. 놀라워요!

고생하셨습니다! ;)

**Comment by qbobl5** [comment]
**<10만원 축하드립니다. 다음번엔 100만원 기원>**
감사합니다!!
