### ISSUE TITLE
너무 잘봤습니다~

### ISSUE THREAD

**Issue by riverkite0708** [woorifisa-service-dev-3rd/frontend-1st-triple_roulette#19]
UI가 직관적이고 의도가 확실히 전해져서 너무 좋은것 같습니다! 
반응형 추후에 업데이트 하신다고 하셨으니 기대하고 있겠습니다 ㅎㅎ 
질문 시간에 나왔던 게임 설명도 추가되면 너무 좋을것 같아요~

**Comment by qbobl5** [comment]
게임 설명 꼭꼭 반영하겠습니다 ^___^!!!! 잘 봐주셔서 감사합니다!
