### ISSUE TITLE
baseball review

### ISSUE THREAD

**Issue by bangsk2** [woorifisa-service-dev-3rd/frontend-1st-triple_roulette#20]
1. UI측면에서 배율에 맞게 확대 축소가 되면 좋을 것 같습니다!
2. 게임방법에 대한 버튼이 추가되면 좋을 것 같습니다!
3. 룰렛에 카테고리를 설정할 수 있도록 하면 일정 범위내에서 값이 도출될 것 같아 사용성에서 다양한 방면에서 적용할 수 있을 것 같습니다! EX) 숫자, 메세지 등

**Comment by qbobl5** [comment]
1. 넵! 반영하도록 하겠습니다.
2. 지적 감사합니다.
3. 좋은 아이디어인 것 같습니다. 꼭 반영해보도록 하겠습니다!
